package ui;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Font;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

import model.User;

public class AdminDashboard extends JFrame {

    private final User user;
    private final MedicinePanel medicinePanel;
    private final SupplierPanel supplierPanel;

    public AdminDashboard(User user) {
        this.user = user;
        this.medicinePanel = new MedicinePanel();
        this.supplierPanel = new SupplierPanel();

        setTitle("PIMS - Admin Dashboard");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout(12, 12));

        JPanel headerPanel = createHeaderPanel();
        JTabbedPane tabbedPane = createTabbedPane();

        add(headerPanel, BorderLayout.NORTH);
        add(tabbedPane, BorderLayout.CENTER);
    }

    private JPanel createHeaderPanel() {
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBorder(BorderFactory.createEmptyBorder(12, 12, 0, 12));

        JLabel titleLabel = new JLabel("Admin Dashboard");
        titleLabel.setFont(new Font("SansSerif", Font.BOLD, 22));

        JLabel welcomeLabel = new JLabel("Welcome, " + user.getFullName());
        welcomeLabel.setFont(new Font("SansSerif", Font.PLAIN, 14));

        headerPanel.add(titleLabel, BorderLayout.NORTH);
        headerPanel.add(welcomeLabel, BorderLayout.SOUTH);
        return headerPanel;
    }

    private JTabbedPane createTabbedPane() {
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.setBorder(BorderFactory.createEmptyBorder(0, 12, 12, 12));

        tabbedPane.addTab("Medicines", medicinePanel);
        tabbedPane.addTab("Suppliers", supplierPanel);
        tabbedPane.addTab(
                "Users",
                createModulePanel(
                        new String[] {"ID", "Username", "Full Name", "Role", "Status", "Created At"}
                )
        );
        tabbedPane.addTab(
                "Reports",
                createModulePanel(
                        new String[] {"ID", "Report Name", "Generated By", "Generated On", "Period", "Notes"}
                )
        );

        tabbedPane.addChangeListener(event -> {
            if (tabbedPane.getSelectedComponent() == medicinePanel) {
                medicinePanel.refreshMedicines();
            } else if (tabbedPane.getSelectedComponent() == supplierPanel) {
                supplierPanel.refreshSuppliers();
            }
        });

        return tabbedPane;
    }

    private JPanel createModulePanel(String[] columns) {
        JPanel modulePanel = new JPanel(new BorderLayout(0, 10));
        modulePanel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        javax.swing.JTable table = new javax.swing.JTable(createTableModel(columns));
        table.setRowHeight(24);
        table.setFillsViewportHeight(true);

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(table);

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 0));
        buttonPanel.add(new JButton("Add"));
        buttonPanel.add(new JButton("Edit"));
        buttonPanel.add(new JButton("Delete"));

        modulePanel.add(scrollPane, BorderLayout.CENTER);
        modulePanel.add(buttonPanel, BorderLayout.SOUTH);
        return modulePanel;
    }

    private DefaultTableModel createTableModel(String[] columns) {
        return new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    }
}
